### ISSUE TITLE
Models hosted on groq don't work when streaming is enabled

### ISSUE THREAD

**Issue by alexagr** [langroid/langroid#828]
When I try to use models hosted on `groq` with streaming enabled, the following Exception is produced:
```
2025-04-21 15:07:05 - ERROR - Error in OpenAIGPT.achat:                                                                                    
Original error: AsyncCompletions.create() got an unexpected keyword argument 'stream_options'                                              
Traceback:                                                                                                                                 
Traceback (most recent call last):                                                                                                         
  File "C:\Projects\CloudServices\AiFramework\venv\Lib\site-packages\langroid\language_models\openai_gpt.py", line 1709, in achat          
    result = await self._achat(                                                                                                            
             ^^^^^^^^^^^^^^^^^^                                                                                                            
  File "C:\Projects\CloudServices\AiFramework\venv\Lib\site-packages\langroid\language_models\openai_gpt.py", line 2121, in _achat         
    cached, hashed_key, response = await self._achat_completions_with_backoff(  # type: ignore                                             
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                             
  File "C:\Projects\CloudServices\AiFramework\venv\Lib\site-packages\langroid\language_models\openai_gpt.py", line 1845, in _achat_completi
ons_with_backoff                                                                                                                           
    return await retry_func(**kwargs)                                                                                                      
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                      
  File "C:\Projects\CloudServices\AiFramework\venv\Lib\site-packages\langroid\language_models\utils.py", line 161, in wrapper              
    raise e                                                                                                                                
  File "C:\Projects\CloudServices\AiFramework\venv\Lib\site-packages\langroid\language_models\utils.py", line 126, in wrapper              
    result = await func(*args, **kwargs)                                                                                                   
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                   
  File "C:\Projects\CloudServices\AiFramework\venv\Lib\site-packages\langroid\language_models\openai_gpt.py", line 1804, in _achat_completi
ons_with_backoff_body                                                                                                                      
    result = await acompletion_call(**kwargs)                                                                                              
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                              
TypeError: AsyncCompletions.create() got an unexpected keyword argument 'stream_options'                                                   
```

This is most probably a regression introduced in #808 .

**Comment by pchalasani** [comment]
thanks for noticing @alexagr  -- fixed in 0.52.7
